<a href="https://colab.research.google.com/github/HarnoorKaur812/Deep-Learning/blob/main/Assign_2_dl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
df=pd.read_csv("glass.csv")

In [3]:
df.head()

        RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [4]:
df.shape,df.columns

((214, 10),
 Index(['RI', 'Na', 'Mg', 'Al', 'Si', 'K', 'Ca', 'Ba', 'Fe', 'Type'], dtype='object'))

In [5]:
df['Type'].unique()

array([1, 2, 3, 5, 6, 7])

In [6]:
df['y']=(df['Type']==1).astype(int)

In [7]:
df['y'].unique()

array([1, 0])

In [8]:
df=df.drop(columns=['Type'])

In [9]:
df.head()

        RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  y
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0  1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0  1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0  1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0  1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0  1

In [10]:
x=df.drop(columns=['y']).values
y=df['y'].values
x,y

(array([[ 1.52101, 13.64   ,  4.49   , ...,  8.75   ,  0.     ,  0.     ],
        [ 1.51761, 13.89   ,  3.6    , ...,  7.83   ,  0.     ,  0.     ],
        [ 1.51618, 13.53   ,  3.55   , ...,  7.78   ,  0.     ,  0.     ],
        ...,
        [ 1.52065, 14.36   ,  0.     , ...,  8.44   ,  1.64   ,  0.     ],
        [ 1.51651, 14.38   ,  0.     , ...,  8.48   ,  1.57   ,  0.     ],
        [ 1.51711, 14.23   ,  0.     , ...,  8.62   ,  1.67   ,  0.     ]]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x, y, test_size=0.2, random_state=15)

In [12]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [13]:
def sigmoid(a):
  return 1/(1+np.exp(-a))

In [14]:
def predict_prob(x,w,b):
  a=np.dot(x,w)+b
  return sigmoid(a)

In [15]:
def loss(y,p):
  return -np.mean(y*np.log(p)+(1-y)*np.log(1-p))

In [16]:
def update(x,y,w,b,lr):
  p=predict_prob(x,w,b)
  e=p-y
  w=w-lr*np.dot(x.T,e)/len(y)
  b=b-lr*np.mean(e)
  return w,b

In [20]:
w=np.zeros(x_train.shape[1])
b=0.0
lr=0.1
epoch=100

In [30]:
for e in range(epoch):
  w,b=update(x_train,y_train,w,b,lr)
  if e%20==0:
    print('Epoch :',e,'\nWeight :',w,'\nBias :',b,'\n\n')

Epoch : 0
Weight : [ 0.52289921 -0.53892117  1.55134439 -1.37114418  0.41507926 -0.13128882
 -0.5793318   0.10557879 -0.13389975]
Bias : -1.6307033629558392


Epoch : 20
Weight : [ 0.53089243 -0.54378421  1.56673558 -1.37995243  0.42310566 -0.1318455
 -0.58522627  0.11235057 -0.1350546 ]
Bias : -1.6423994964668396


Epoch : 40
Weight : [ 0.53872152 -0.54845151  1.58174937 -1.38835242  0.43094812 -0.13237233
 -0.59091241  0.11902862 -0.13616251]
Bias : -1.653685762544455


Epoch : 60
Weight : [ 0.54639145 -0.55293195  1.59640225 -1.39636535  0.43861414 -0.13287076
 -0.59639724  0.12561452 -0.13722588]
Bias : -1.6645816622433085


Epoch : 80
Weight : [ 0.55390694 -0.55723383  1.61070966 -1.40401098  0.44611086 -0.13334211
 -0.60168743  0.13210986 -0.13824694]
Bias : -1.675105402849481

In [31]:
def predict_label(p,threshold):
  return (p>=threshold).astype(int)

In [32]:
p=predict_prob(x_test,w,b)

In [33]:
#Threshold=0.5

y_pred=predict_label(p,0.5)
acc=np.mean(y_pred==y_test)
print('Accuracy with threshold=0.5 :',acc)

Accuracy with threshold=0.5 : 0.7441860465116279

In [35]:
#Threshold=0.7

y_pred=predict_label(p,0.7)
acc=np.mean(y_pred==y_test)
print('Accuracy with threshold=0.7 :',acc)

Accuracy with threshold=0.7 : 0.7209302325581395